package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private String idCategoria;
     private String nombreCategoria;
     private String estado;
     private Set productos = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(String idCategoria) {
        this.idCategoria = idCategoria;
    }
    public Categoria(String idCategoria, String nombreCategoria, String estado, Set productos) {
       this.idCategoria = idCategoria;
       this.nombreCategoria = nombreCategoria;
       this.estado = estado;
       this.productos = productos;
    }
   
    public String getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(String idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


