package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CompraDevolucion generated by hbm2java
 */
public class CompraDevolucion  implements java.io.Serializable {


     private String idDevolucion;
     private Usuario usuario;
     private Date fechaDevolucion;
     private Set detalleCompraDevs = new HashSet(0);

    public CompraDevolucion() {
    }

	
    public CompraDevolucion(String idDevolucion) {
        this.idDevolucion = idDevolucion;
    }
    public CompraDevolucion(String idDevolucion, Usuario usuario, Date fechaDevolucion, Set detalleCompraDevs) {
       this.idDevolucion = idDevolucion;
       this.usuario = usuario;
       this.fechaDevolucion = fechaDevolucion;
       this.detalleCompraDevs = detalleCompraDevs;
    }
   
    public String getIdDevolucion() {
        return this.idDevolucion;
    }
    
    public void setIdDevolucion(String idDevolucion) {
        this.idDevolucion = idDevolucion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
    public Set getDetalleCompraDevs() {
        return this.detalleCompraDevs;
    }
    
    public void setDetalleCompraDevs(Set detalleCompraDevs) {
        this.detalleCompraDevs = detalleCompraDevs;
    }




}


