package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private String idCompra;
     private Usuario usuario;
     private Comprobante comprobante;
     private Proveedor proveedor;
     private String numComprobante;
     private Date fechaCompra;
     private Double total;
     private String descripcion;
     private Set detalleCompras = new HashSet(0);

    public Compra() {
    }

	
    public Compra(String idCompra, String numComprobante, Date fechaCompra) {
        this.idCompra = idCompra;
        this.numComprobante = numComprobante;
        this.fechaCompra = fechaCompra;
    }
    public Compra(String idCompra, Usuario usuario, Comprobante comprobante, Proveedor proveedor, String numComprobante, Date fechaCompra, Double total, String descripcion, Set detalleCompras) {
       this.idCompra = idCompra;
       this.usuario = usuario;
       this.comprobante = comprobante;
       this.proveedor = proveedor;
       this.numComprobante = numComprobante;
       this.fechaCompra = fechaCompra;
       this.total = total;
       this.descripcion = descripcion;
       this.detalleCompras = detalleCompras;
    }
   
    public String getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(String idCompra) {
        this.idCompra = idCompra;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Comprobante getComprobante() {
        return this.comprobante;
    }
    
    public void setComprobante(Comprobante comprobante) {
        this.comprobante = comprobante;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNumComprobante() {
        return this.numComprobante;
    }
    
    public void setNumComprobante(String numComprobante) {
        this.numComprobante = numComprobante;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getDetalleCompras() {
        return this.detalleCompras;
    }
    
    public void setDetalleCompras(Set detalleCompras) {
        this.detalleCompras = detalleCompras;
    }




}


