package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Comprobante generated by hbm2java
 */
public class Comprobante  implements java.io.Serializable {


     private String idComprobante;
     private String nombreComprobante;
     private Set compras = new HashSet(0);
     private Set ventas = new HashSet(0);

    public Comprobante() {
    }

	
    public Comprobante(String idComprobante, String nombreComprobante) {
        this.idComprobante = idComprobante;
        this.nombreComprobante = nombreComprobante;
    }
    public Comprobante(String idComprobante, String nombreComprobante, Set compras, Set ventas) {
       this.idComprobante = idComprobante;
       this.nombreComprobante = nombreComprobante;
       this.compras = compras;
       this.ventas = ventas;
    }
   
    public String getIdComprobante() {
        return this.idComprobante;
    }
    
    public void setIdComprobante(String idComprobante) {
        this.idComprobante = idComprobante;
    }
    public String getNombreComprobante() {
        return this.nombreComprobante;
    }
    
    public void setNombreComprobante(String nombreComprobante) {
        this.nombreComprobante = nombreComprobante;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


