package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1



/**
 * DetalleCompraDevId generated by hbm2java
 */
public class DetalleCompraDevId  implements java.io.Serializable {


     private String idDevolucion;
     private String idCompra;
     private String idProducto;

    public DetalleCompraDevId() {
    }

    public DetalleCompraDevId(String idDevolucion, String idCompra, String idProducto) {
       this.idDevolucion = idDevolucion;
       this.idCompra = idCompra;
       this.idProducto = idProducto;
    }
   
    public String getIdDevolucion() {
        return this.idDevolucion;
    }
    
    public void setIdDevolucion(String idDevolucion) {
        this.idDevolucion = idDevolucion;
    }
    public String getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(String idCompra) {
        this.idCompra = idCompra;
    }
    public String getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(String idProducto) {
        this.idProducto = idProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleCompraDevId) ) return false;
		 DetalleCompraDevId castOther = ( DetalleCompraDevId ) other; 
         
		 return ( (this.getIdDevolucion()==castOther.getIdDevolucion()) || ( this.getIdDevolucion()!=null && castOther.getIdDevolucion()!=null && this.getIdDevolucion().equals(castOther.getIdDevolucion()) ) )
 && ( (this.getIdCompra()==castOther.getIdCompra()) || ( this.getIdCompra()!=null && castOther.getIdCompra()!=null && this.getIdCompra().equals(castOther.getIdCompra()) ) )
 && ( (this.getIdProducto()==castOther.getIdProducto()) || ( this.getIdProducto()!=null && castOther.getIdProducto()!=null && this.getIdProducto().equals(castOther.getIdProducto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdDevolucion() == null ? 0 : this.getIdDevolucion().hashCode() );
         result = 37 * result + ( getIdCompra() == null ? 0 : this.getIdCompra().hashCode() );
         result = 37 * result + ( getIdProducto() == null ? 0 : this.getIdProducto().hashCode() );
         return result;
   }   


}


