package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * DetalleCompra generated by hbm2java
 */
public class DetalleCompra  implements java.io.Serializable {


     private DetalleCompraId id;
     private Compra compra;
     private Producto producto;
     private BigDecimal cantidad;
     private Double precioUnitario;
     private Set detalleCompraDevs = new HashSet(0);
     private ProductoDetalle productoDetalle;

    public DetalleCompra() {
    }

	
    public DetalleCompra(DetalleCompraId id, Compra compra, Producto producto) {
        this.id = id;
        this.compra = compra;
        this.producto = producto;
    }
    public DetalleCompra(DetalleCompraId id, Compra compra, Producto producto, BigDecimal cantidad, Double precioUnitario, Set detalleCompraDevs, ProductoDetalle productoDetalle) {
       this.id = id;
       this.compra = compra;
       this.producto = producto;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
       this.detalleCompraDevs = detalleCompraDevs;
       this.productoDetalle = productoDetalle;
    }
   
    public DetalleCompraId getId() {
        return this.id;
    }
    
    public void setId(DetalleCompraId id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public Double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(Double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public Set getDetalleCompraDevs() {
        return this.detalleCompraDevs;
    }
    
    public void setDetalleCompraDevs(Set detalleCompraDevs) {
        this.detalleCompraDevs = detalleCompraDevs;
    }
    public ProductoDetalle getProductoDetalle() {
        return this.productoDetalle;
    }
    
    public void setProductoDetalle(ProductoDetalle productoDetalle) {
        this.productoDetalle = productoDetalle;
    }




}


