package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleDevolucion generated by hbm2java
 */
public class DetalleDevolucion  implements java.io.Serializable {


     private DetalleDevolucionId id;
     private Devolucion devolucion;
     private DetalleVenta detalleVenta;
     private BigDecimal cantidad;
     private Double precioUnitario;
     private String motivo;

    public DetalleDevolucion() {
    }

	
    public DetalleDevolucion(DetalleDevolucionId id, Devolucion devolucion, DetalleVenta detalleVenta) {
        this.id = id;
        this.devolucion = devolucion;
        this.detalleVenta = detalleVenta;
    }
    public DetalleDevolucion(DetalleDevolucionId id, Devolucion devolucion, DetalleVenta detalleVenta, BigDecimal cantidad, Double precioUnitario, String motivo) {
       this.id = id;
       this.devolucion = devolucion;
       this.detalleVenta = detalleVenta;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
       this.motivo = motivo;
    }
   
    public DetalleDevolucionId getId() {
        return this.id;
    }
    
    public void setId(DetalleDevolucionId id) {
        this.id = id;
    }
    public Devolucion getDevolucion() {
        return this.devolucion;
    }
    
    public void setDevolucion(Devolucion devolucion) {
        this.devolucion = devolucion;
    }
    public DetalleVenta getDetalleVenta() {
        return this.detalleVenta;
    }
    
    public void setDetalleVenta(DetalleVenta detalleVenta) {
        this.detalleVenta = detalleVenta;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public Double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(Double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }




}


