package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1



/**
 * DetalleDevolucionId generated by hbm2java
 */
public class DetalleDevolucionId  implements java.io.Serializable {


     private String idDevolucion;
     private String idVenta;
     private String idProducto;

    public DetalleDevolucionId() {
    }

    public DetalleDevolucionId(String idDevolucion, String idVenta, String idProducto) {
       this.idDevolucion = idDevolucion;
       this.idVenta = idVenta;
       this.idProducto = idProducto;
    }
   
    public String getIdDevolucion() {
        return this.idDevolucion;
    }
    
    public void setIdDevolucion(String idDevolucion) {
        this.idDevolucion = idDevolucion;
    }
    public String getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(String idVenta) {
        this.idVenta = idVenta;
    }
    public String getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(String idProducto) {
        this.idProducto = idProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleDevolucionId) ) return false;
		 DetalleDevolucionId castOther = ( DetalleDevolucionId ) other; 
         
		 return ( (this.getIdDevolucion()==castOther.getIdDevolucion()) || ( this.getIdDevolucion()!=null && castOther.getIdDevolucion()!=null && this.getIdDevolucion().equals(castOther.getIdDevolucion()) ) )
 && ( (this.getIdVenta()==castOther.getIdVenta()) || ( this.getIdVenta()!=null && castOther.getIdVenta()!=null && this.getIdVenta().equals(castOther.getIdVenta()) ) )
 && ( (this.getIdProducto()==castOther.getIdProducto()) || ( this.getIdProducto()!=null && castOther.getIdProducto()!=null && this.getIdProducto().equals(castOther.getIdProducto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdDevolucion() == null ? 0 : this.getIdDevolucion().hashCode() );
         result = 37 * result + ( getIdVenta() == null ? 0 : this.getIdVenta().hashCode() );
         result = 37 * result + ( getIdProducto() == null ? 0 : this.getIdProducto().hashCode() );
         return result;
   }   


}


