package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleCompraDev generated by hbm2java
 */
public class DetalleCompraDev  implements java.io.Serializable {


     private DetalleCompraDevId id;
     private CompraDevolucion compraDevolucion;
     private DetalleCompra detalleCompra;
     private BigDecimal cantidad;
     private Double precioUnitario;
     private String motivo;

    public DetalleCompraDev() {
    }

	
    public DetalleCompraDev(DetalleCompraDevId id, CompraDevolucion compraDevolucion, DetalleCompra detalleCompra) {
        this.id = id;
        this.compraDevolucion = compraDevolucion;
        this.detalleCompra = detalleCompra;
    }
    public DetalleCompraDev(DetalleCompraDevId id, CompraDevolucion compraDevolucion, DetalleCompra detalleCompra, BigDecimal cantidad, Double precioUnitario, String motivo) {
       this.id = id;
       this.compraDevolucion = compraDevolucion;
       this.detalleCompra = detalleCompra;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
       this.motivo = motivo;
    }
   
    public DetalleCompraDevId getId() {
        return this.id;
    }
    
    public void setId(DetalleCompraDevId id) {
        this.id = id;
    }
    public CompraDevolucion getCompraDevolucion() {
        return this.compraDevolucion;
    }
    
    public void setCompraDevolucion(CompraDevolucion compraDevolucion) {
        this.compraDevolucion = compraDevolucion;
    }
    public DetalleCompra getDetalleCompra() {
        return this.detalleCompra;
    }
    
    public void setDetalleCompra(DetalleCompra detalleCompra) {
        this.detalleCompra = detalleCompra;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public Double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(Double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }




}


