package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Devolucion generated by hbm2java
 */
public class Devolucion  implements java.io.Serializable {


     private String idDevolucion;
     private Usuario usuario;
     private Date fechaDevolucion;
     private Set detalleDevolucions = new HashSet(0);

    public Devolucion() {
    }

	
    public Devolucion(String idDevolucion) {
        this.idDevolucion = idDevolucion;
    }
    public Devolucion(String idDevolucion, Usuario usuario, Date fechaDevolucion, Set detalleDevolucions) {
       this.idDevolucion = idDevolucion;
       this.usuario = usuario;
       this.fechaDevolucion = fechaDevolucion;
       this.detalleDevolucions = detalleDevolucions;
    }
   
    public String getIdDevolucion() {
        return this.idDevolucion;
    }
    
    public void setIdDevolucion(String idDevolucion) {
        this.idDevolucion = idDevolucion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
    public Set getDetalleDevolucions() {
        return this.detalleDevolucions;
    }
    
    public void setDetalleDevolucions(Set detalleDevolucions) {
        this.detalleDevolucions = detalleDevolucions;
    }




}


