package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private String idMarca;
     private String nombreMarca;
     private String estado;
     private Set productos = new HashSet(0);

    public Marca() {
    }

	
    public Marca(String idMarca) {
        this.idMarca = idMarca;
    }
    public Marca(String idMarca, String nombreMarca, String estado, Set productos) {
       this.idMarca = idMarca;
       this.nombreMarca = nombreMarca;
       this.estado = estado;
       this.productos = productos;
    }
   
    public String getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(String idMarca) {
        this.idMarca = idMarca;
    }
    public String getNombreMarca() {
        return this.nombreMarca;
    }
    
    public void setNombreMarca(String nombreMarca) {
        this.nombreMarca = nombreMarca;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


