package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private String idProducto;
     private Ubicacion ubicacion;
     private Categoria categoria;
     private Marca marca;
//   private UndMedida undMedida;
     private String id_categoria;
     private String id_marca;
     private String id_ubicacion;
     private String UndMedida;
     private String id_unidad;
     private String cantidad;
     private String codigo;
     private String nombre;
     private String medida;
     private String fechaReg;
     private Double precioPublico;
     private Double precioMayor;
     private Double precioCredito;
     private Double precioCompra;
     private Double Porc_mayor;
     private Double Porc_cred;
     private Double Porc_pub;
     private Double igv;
     private Double flete;
     private String color;
     private String descripcion;
     private Set detalleCompras = new HashSet(0);
     private Set detalleVentas = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String idProducto) {
        this.idProducto = idProducto;
    }

    public Producto(String idProducto, Ubicacion ubicacion, Categoria categoria, Marca marca, String id_categoria, String id_marca, String id_ubicacion, String UndMedida, String id_unidad, String cantidad, String codigo, String nombre, String medida, String fechaReg, Double precioPublico, Double precioMayor, Double precioCredito, String color, String descripcion) {
        this.idProducto = idProducto;
        this.ubicacion = ubicacion;
        this.categoria = categoria;
        this.marca = marca;
        this.id_categoria = id_categoria;
        this.id_marca = id_marca;
        this.id_ubicacion = id_ubicacion;
        this.UndMedida = UndMedida;
        this.id_unidad = id_unidad;
        this.cantidad = cantidad;
        this.codigo = codigo;
        this.nombre = nombre;
        this.medida = medida;
        this.fechaReg = fechaReg;
        this.precioPublico = precioPublico;
        this.precioMayor = precioMayor;
        this.precioCredito = precioCredito;
        this.color = color;
        this.descripcion = descripcion;
    }

    public String getIdProducto() {
        return idProducto;
    }

    public void setIdProducto(String idProducto) {
        this.idProducto = idProducto;
    }

    public Ubicacion getUbicacion() {
        return ubicacion;
    }

    public void setUbicacion(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }

    public Categoria getCategoria() {
        return categoria;
    }

    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    public Marca getMarca() {
        return marca;
    }

    public void setMarca(Marca marca) {
        this.marca = marca;
    }

    public String getId_categoria() {
        return id_categoria;
    }

    public void setId_categoria(String id_categoria) {
        this.id_categoria = id_categoria;
    }

    public String getId_marca() {
        return id_marca;
    }

    public void setId_marca(String id_marca) {
        this.id_marca = id_marca;
    }

    public String getId_ubicacion() {
        return id_ubicacion;
    }

    public void setId_ubicacion(String id_ubicacion) {
        this.id_ubicacion = id_ubicacion;
    }

    public String getUndMedida() {
        return UndMedida;
    }

    public void setUndMedida(String UndMedida) {
        this.UndMedida = UndMedida;
    }

    public String getId_unidad() {
        return id_unidad;
    }

    public void setId_unidad(String id_unidad) {
        this.id_unidad = id_unidad;
    }

    public String getCantidad() {
        return cantidad;
    }

    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getMedida() {
        return medida;
    }

    public void setMedida(String medida) {
        this.medida = medida;
    }

    public String getFechaReg() {
        return fechaReg;
    }

    public void setFechaReg(String fechaReg) {
        this.fechaReg = fechaReg;
    }

    public Double getPrecioPublico() {
        return precioPublico;
    }

    public void setPrecioPublico(Double precioPublico) {
        this.precioPublico = precioPublico;
    }

    public Double getPrecioMayor() {
        return precioMayor;
    }

    public void setPrecioMayor(Double precioMayor) {
        this.precioMayor = precioMayor;
    }

    public Double getPrecioCredito() {
        return precioCredito;
    }

    public void setPrecioCredito(Double precioCredito) {
        this.precioCredito = precioCredito;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set getDetalleCompras() {
        return detalleCompras;
    }

    public void setDetalleCompras(Set detalleCompras) {
        this.detalleCompras = detalleCompras;
    }

    public Set getDetalleVentas() {
        return detalleVentas;
    }

    public void setDetalleVentas(Set detalleVentas) {
        this.detalleVentas = detalleVentas;
    }

    public Double getPrecioCompra() {
        return precioCompra;
    }

    public void setPrecioCompra(Double precioCompra) {
        this.precioCompra = precioCompra;
    }

    public Double getPorc_mayor() {
        return Porc_mayor;
    }

    public void setPorc_mayor(Double Porc_mayor) {
        this.Porc_mayor = Porc_mayor;
    }

    public Double getPorc_cred() {
        return Porc_cred;
    }

    public void setPorc_cred(Double Porc_cred) {
        this.Porc_cred = Porc_cred;
    }

    public Double getPorc_pub() {
        return Porc_pub;
    }

    public void setPorc_pub(Double Porc_pub) {
        this.Porc_pub = Porc_pub;
    }

    public Double getIgv() {
        return igv;
    }

    public void setIgv(Double igv) {
        this.igv = igv;
    }

    public Double getFlete() {
        return flete;
    }

    public void setFlete(Double flete) {
        this.flete = flete;
    }
    
    
    
}


