package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ProductoDetalle generated by hbm2java
 */
public class ProductoDetalle  implements java.io.Serializable {


     private ProductoDetalleId id;
     private DetalleCompra detalleCompra;
     private Date fechaRegistro;
     private BigDecimal precioVentaMayor;
     private BigDecimal precioVentaPublico;
     private BigDecimal precioVentaCredito;
     private BigDecimal stockMin;
     private BigDecimal stockMax;

    public ProductoDetalle() {
    }

	
    public ProductoDetalle(DetalleCompra detalleCompra) {
        this.detalleCompra = detalleCompra;
    }
    public ProductoDetalle(DetalleCompra detalleCompra, Date fechaRegistro, BigDecimal precioVentaMayor, BigDecimal precioVentaPublico, BigDecimal precioVentaCredito, BigDecimal stockMin, BigDecimal stockMax) {
       this.detalleCompra = detalleCompra;
       this.fechaRegistro = fechaRegistro;
       this.precioVentaMayor = precioVentaMayor;
       this.precioVentaPublico = precioVentaPublico;
       this.precioVentaCredito = precioVentaCredito;
       this.stockMin = stockMin;
       this.stockMax = stockMax;
    }
   
    public ProductoDetalleId getId() {
        return this.id;
    }
    
    public void setId(ProductoDetalleId id) {
        this.id = id;
    }
    public DetalleCompra getDetalleCompra() {
        return this.detalleCompra;
    }
    
    public void setDetalleCompra(DetalleCompra detalleCompra) {
        this.detalleCompra = detalleCompra;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public BigDecimal getPrecioVentaMayor() {
        return this.precioVentaMayor;
    }
    
    public void setPrecioVentaMayor(BigDecimal precioVentaMayor) {
        this.precioVentaMayor = precioVentaMayor;
    }
    public BigDecimal getPrecioVentaPublico() {
        return this.precioVentaPublico;
    }
    
    public void setPrecioVentaPublico(BigDecimal precioVentaPublico) {
        this.precioVentaPublico = precioVentaPublico;
    }
    public BigDecimal getPrecioVentaCredito() {
        return this.precioVentaCredito;
    }
    
    public void setPrecioVentaCredito(BigDecimal precioVentaCredito) {
        this.precioVentaCredito = precioVentaCredito;
    }
    public BigDecimal getStockMin() {
        return this.stockMin;
    }
    
    public void setStockMin(BigDecimal stockMin) {
        this.stockMin = stockMin;
    }
    public BigDecimal getStockMax() {
        return this.stockMax;
    }
    
    public void setStockMax(BigDecimal stockMax) {
        this.stockMax = stockMax;
    }




}


