package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private String idProveedor;
     private Persona persona;
     private String correoElectronico;
     private Set compras = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(Persona persona) {
        this.persona = persona;
    }
    public Proveedor(Persona persona, String correoElectronico, Set compras) {
       this.persona = persona;
       this.correoElectronico = correoElectronico;
       this.compras = compras;
    }
   
    public String getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(String idProveedor) {
        this.idProveedor = idProveedor;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


