package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private String idTipoUsuario;
     private String nombre;
     private Set usuarios = new HashSet(0);

    public TipoUsuario() {
    }

	
    public TipoUsuario(String idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public TipoUsuario(String idTipoUsuario, String nombre, Set usuarios) {
       this.idTipoUsuario = idTipoUsuario;
       this.nombre = nombre;
       this.usuarios = usuarios;
    }
   
    public String getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(String idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


