package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumento generated by hbm2java
 */
public class TipoDocumento  implements java.io.Serializable {


     private String idTipoDocumento;
     private String nombre;
     private Set personas = new HashSet(0);

    public TipoDocumento() {
    }

	
    public TipoDocumento(String idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }
    public TipoDocumento(String idTipoDocumento, String nombre, Set personas) {
       this.idTipoDocumento = idTipoDocumento;
       this.nombre = nombre;
       this.personas = personas;
    }
   
    public String getIdTipoDocumento() {
        return this.idTipoDocumento;
    }
    
    public void setIdTipoDocumento(String idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


