package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ubicacion generated by hbm2java
 */
public class Ubicacion  implements java.io.Serializable {


     private String idUbicacion;
     private String nombreUbicacion;
     private String estado;
     private Set productos = new HashSet(0);

    public Ubicacion() {
    }

	
    public Ubicacion(String idUbicacion) {
        this.idUbicacion = idUbicacion;
    }
    public Ubicacion(String idUbicacion, String nombreUbicacion, String estado, Set productos) {
       this.idUbicacion = idUbicacion;
       this.nombreUbicacion = nombreUbicacion;
       this.estado = estado;
       this.productos = productos;
    }
   
    public String getIdUbicacion() {
        return this.idUbicacion;
    }
    
    public void setIdUbicacion(String idUbicacion) {
        this.idUbicacion = idUbicacion;
    }
    public String getNombreUbicacion() {
        return this.nombreUbicacion;
    }
    
    public void setNombreUbicacion(String nombreUbicacion) {
        this.nombreUbicacion = nombreUbicacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


