package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UndMedida generated by hbm2java
 */
public class UndMedida  implements java.io.Serializable {


     private String idUndMedida;
     private String nombre;
     private String abreviatura;
     private Set productos = new HashSet(0);

    public UndMedida() {
    }

	
    public UndMedida(String idUndMedida, String nombre) {
        this.idUndMedida = idUndMedida;
        this.nombre = nombre;
    }
    public UndMedida(String idUndMedida, String nombre, String abreviatura, Set productos) {
       this.idUndMedida = idUndMedida;
       this.nombre = nombre;
       this.abreviatura = abreviatura;
       this.productos = productos;
    }
   
    public String getIdUndMedida() {
        return this.idUndMedida;
    }
    
    public void setIdUndMedida(String idUndMedida) {
        this.idUndMedida = idUndMedida;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


