package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String idUsuario;
     private TipoUsuario tipoUsuario;
     private Persona persona;
     private String login;
     private String password;
     private String estado;
     private Set compras = new HashSet(0);
     private Set ventas = new HashSet(0);
     private Set compraDevolucions = new HashSet(0);
     private Set devolucions = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(Persona persona, String login, String password, String estado) {
        this.persona = persona;
        this.login = login;
        this.password = password;
        this.estado = estado;
    }
    public Usuario(TipoUsuario tipoUsuario, Persona persona, String login, String password, String estado, Set compras, Set ventas, Set compraDevolucions, Set devolucions) {
       this.tipoUsuario = tipoUsuario;
       this.persona = persona;
       this.login = login;
       this.password = password;
       this.estado = estado;
       this.compras = compras;
       this.ventas = ventas;
       this.compraDevolucions = compraDevolucions;
       this.devolucions = devolucions;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }
    public Set getCompraDevolucions() {
        return this.compraDevolucions;
    }
    
    public void setCompraDevolucions(Set compraDevolucions) {
        this.compraDevolucions = compraDevolucions;
    }
    public Set getDevolucions() {
        return this.devolucions;
    }
    
    public void setDevolucions(Set devolucions) {
        this.devolucions = devolucions;
    }




}


