package proy01.modelo.entidad;
// Generated 07/05/2015 07:26:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private String idVenta;
     private Usuario usuario;
     private Comprobante comprobante;
     private Cliente cliente;
     private Date fechaVenta;
     private String numComprobante;
     private Set detalleVentas = new HashSet(0);

    public Venta() {
    }

	
    public Venta(String idVenta) {
        this.idVenta = idVenta;
    }
    public Venta(String idVenta, Usuario usuario, Comprobante comprobante, Cliente cliente, Date fechaVenta, String numComprobante, Set detalleVentas) {
       this.idVenta = idVenta;
       this.usuario = usuario;
       this.comprobante = comprobante;
       this.cliente = cliente;
       this.fechaVenta = fechaVenta;
       this.numComprobante = numComprobante;
       this.detalleVentas = detalleVentas;
    }
   
    public String getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(String idVenta) {
        this.idVenta = idVenta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Comprobante getComprobante() {
        return this.comprobante;
    }
    
    public void setComprobante(Comprobante comprobante) {
        this.comprobante = comprobante;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public String getNumComprobante() {
        return this.numComprobante;
    }
    
    public void setNumComprobante(String numComprobante) {
        this.numComprobante = numComprobante;
    }
    public Set getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set detalleVentas) {
        this.detalleVentas = detalleVentas;
    }




}


